### ISSUE TITLE
Use of parameters via python driver seems to break Dozer enhanced images

### ISSUE THREAD

**Issue by Johnno1011** [DozerDB/dozerdb-core#32]
Hi guys! Great that I was able to get dozer up and running! Unfortunately I think perhaps the recent feature allowing dropping of databases might still be unstable. I'll share my findings here.

docker-compose.yml
```
services:
  dozer-neo4j:
    image: graphstack/dozerdb:5.25.1
    container_name: neo4j-test
    restart: always
    ports:
      - 7700:7474
      - 7701:7687
    volumes:
      - ./plugins:/plugins
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/neo4j
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*, db.*, gds.*, dozer.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*, db.*, apoc.meta.data(), gds.*, dozer.*

volumes:
  neo4j_data:
```
In /plugins I inserted open-gds-2.8.0-alpha01.jar mentioned [here](https://github.com/DozerDB/dozerdb-plugin/issues/32#issuecomment-2477282943) and apoc-5.15.1-core.jar from [here](https://github.com/neo4j/apoc/releases/tag/5.25.1).

Now, from the web interface of Neo4j, I'm able to create multiple databases with `CREATE DATABASE` and delete them as I please with `DROP DATABASE`.

Using the python client ([5.26.0 - Neo4j Bolt driver for Python](https://github.com/neo4j/neo4j-python-driver/releases/tag/5.25.0)). I can sometimes create a database as shown below, but this does not work robustly, if I keep adding new ones eventually something goes wrong.
```
from neo4j import GraphDatabase

params = {"databaseName": "pikachu"}
query = "CREATE DATABASE $databaseName"
database = None

with GraphDatabase.driver(
    services["graph_store_url"], auth=("neo4j", "neo4j")
) as driver:
    with driver.session(database=database) as session:
        result = session.run(query, parameters=params)  # type: ignore
        print([r.data() for r in result])
```
When trying to then do anything using these databases (for example add new data with new properties using `MATCH` statements), I get the following error from the python client:
<img width="965" alt="image" src="https://github.com/user-attachments/assets/a133779a-9e53-479f-b33a-33504516e58f">

After this happens, the frontend UI appears to show the container is a bit fragged and the container logs of course complain that it cannot perform the next operation since the DB doesn't exist and got corrupted in some way (I have to destroy and reinitialise the container and DB volume).
![image](https://github.com/user-attachments/assets/feeb05c3-e656-4923-9fab-a39cf826e240)
![image](https://github.com/user-attachments/assets/053f0a00-916c-4a76-9967-3c288e39191e)

I hope this is enough information to get a discussion going around this topic and reproduction of what I'm experiencing. Please let me know if there's anything else you need. Thanks !
